// <auto-generated />
using System;
using CRUD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace react_back.Migrations
{
    [DbContext(typeof(DBConnection))]
    [Migration("20230510192606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("react_back.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Company")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "company");

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<DateTime>("Create_at")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "create_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("First")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "first");

                    b.Property<string>("Last")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "last");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
